[package]
name = "karu"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
ratatui = { version = "0.26.2", features = ["crossterm"] }
trash = "3.1.0"
nerd-font-symbols = "0.3.0"
unicode-width = "0.1.11"
image = "0.25.1"
viuer = "0.8.0"


